# Generated by Django 6.0 on 2025-12-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_comment_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='The keyword to listen for (case-insensitive).', max_length=100, unique=True)),
            ],
        ),
    ]
